site_name: Django Ninja
site_description: Django Ninja - Django REST framework with high performance, easy to learn, fast to code.
site_url: https://django-ninja.dev
repo_name: vitalik/django-ninja
repo_url: https://github.com/vitalik/django-ninja
edit_uri: ""
extra:
  analytics:
    provider: google
    property: G-0E3XZ663ZR
extra_css:
  - extra.css
extra_javascript:
  - javascripts/ask-ai-button.js
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      primary: green
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: green
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  logo: img/docs-logo.png
  favicon: img/favicon.svg
  language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.footer
    - navigation.top
    - content.code.copy
    - search.highlight
    - search.suggest
  icon:
    repo: fontawesome/brands/github-alt
nav:
  - Home:
      - index.md
      - motivation.md
  - Quick Start:
      - quickstart/index.md
      - quickstart/models-and-schemas.md
      - quickstart/next-steps.md
  - Tutorial:
      - tutorial/index.md
      - tutorial/part-1.md
      - tutorial/part-2.md
      - tutorial/part-3.md
      - tutorial/part-4.md
  - Guide:
      - guide/index.md
      - guide/api.md
      - guide/operations.md
      - guide/routers.md
      - guide/urls.md
      - guide/path-params.md
      - guide/query-params.md
      - guide/body.md
      - guide/forms.md
      - guide/files.md
      - guide/headers-cookies.md
      - guide/parsers.md
      - guide/schemas.md
      - guide/model-schema.md
      - guide/create-schema.md
      - guide/schema-config.md
      - guide/responses.md
      - guide/temporal-response.md
      - guide/renderers.md
      - guide/pagination.md
      - guide/filtering.md
      - guide/authentication.md
      - guide/csrf.md
      - guide/throttling.md
      - guide/errors.md
      - guide/decorators.md
      - guide/async.md
      - guide/versioning.md
      - guide/openapi.md
      - guide/testing.md
      - guide/settings.md
not_in_nav: |
  /legacy/
  /proposals/
  help.md
  releases.md
  whatsnew_v1.md
  chat.md
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - search
