name: Test Coverage

on:
  push:
    branches:
      - master

env:
  UV_NO_SYNC: "true"

jobs:
  test_coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Set up uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          version: '0.11.32'
          python-version: '3.12'
          enable-cache: true
      - name: Install Dependencies
        run: uv sync --locked --no-default-groups --group test
      - name: Test
        run: uv run pytest --cov=ninja --cov-report=xml tests
      - name: Coverage
        uses: codecov/codecov-action@v5.5.2
